version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=vaalikoppi
      - MYSQL_USER=vaalikoppi
      - MYSQL_PASSWORD=secret
  web:
    tty: true
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://vaalikoppi:secret@db/vaalikoppi
