version: "3"

services:
  vaalikoppi:
    image: prodekoregistry.azurecr.io/prodeko-org/prodeko-org:latest
    restart: unless-stopped
    command: waitress-serve --threads 5 --port=8000 election.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=election.settings.prod
      - SECRET_KEY=ANSIBLE_REPLACE_SECRET_KEY
      - DB_PASSWORD=ANSIBLE_REPLACE_DB_PASSWORD
      - DB_USER=user_vaalikoppi@prodeko-postgres
      - POSTGRESQL_SSL_CA=/code/ca-certs/CombinedCa.crt.pem
      - SENTRY_DSN=https://dda0512eee65464c893202702005be39@sentry.prodeko.org/4

networks:
  default:
    external:
      name: prodeko-docker-net
