name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose stack
        run: docker-compose up -d

      # Should not do it like this...
      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "15s"

      - name: Run linters
        run: docker exec vaalikoppi curlylint vaalikoppi

      - name: Run tests
        run: docker exec vaalikoppi pytest --cov --cov-report=xml election/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
